### ISSUE TITLE
Introduce metrics about issues

### ISSUE THREAD

**Issue by porridge** [cncf/devstats.archive#10]
Please show issue filing/closing rates for example. Ideally broken down by kind and SIG.

**Comment by lukaszgryglicki** [comment]
I'll work on this.

**Comment by lukaszgryglicki** [comment]
I'll create two metrics for this. 
- One that will be broken down by SIG and kind (including "All" for both SIG and Kind).
- Another one for issues filled and closed broken down by repository groups.

Why? Because some issues have no labels applied, so second metric will just show all issues in repository groups no matter labels.

**Comment by lukaszgryglicki** [comment]
Implemented:
Issues filled/closed broken down by Repository groups (including All): https://devstats.k8s.io/dashboard/db/issues-repository-group?orgId=1
Issues filled/closed broken down by SIGs and Kinds (including All for both): https://devstats.k8s.io/dashboard/db/sig-issues?orgId=1

Closing.
