### ISSUE TITLE
Rename select charts

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#104]
The Devstats subproject of SIG-Contribex has reviewed the existing charts and tables, and would like to rename the following ones to provide better clarity of the purpose and contents of the chart through its name:

|  Old Name | New Name |
|  ------ | ------ |
|  Companies statistics repository groups | Company Statistics by Repository Group |
|  SIG issues | Issues Opened/Closed by SIG |
|  New And Episodic Issues repository groups | New And Episodic Issue Creators |
|  New And Episodic Contributors repository groups | New and Episodic PR Contributors |
|  PRs Age repository groups | Open PR Age By Repository Group |
|  Project Statistics Table | Overall Project Statistics |
|  User reviews | PR Reviews by Contributor |
|  First non author activity repository groups | PR Time to Engagment |
|  Opened to Merged repository groups | PR Time to merge |
|  PR Workload by SIGs | PR Workload per SIG Chart |
|  PR  Workload by SIGs Table | PR Workload per SIG Table |
|  Community Stats repositories | Stars and Forks by Repository |

**Comment by jberkus** [comment]
Assigning to @Phillels for final approval.

**Comment by lukaszgryglicki** [comment]
BTW: old links will still work because:

- https://k8s.devstats.cncf.io/d/6/commits-repository-groups?orgId=1
- https://k8s.devstats.cncf.io/d/6/abc?orgId=1

Makes no difference for Grafana. It only cares about `6` - uid value for a given dashboard.
If you put wrong name slug after the uid you will be redirected to the correct dashboard link with this uid (or nowhere if there is no such `uid`)

Real example:
- "SIG issues" -> "Issues Opened/Closed by SIG"
- Old link: https://k8s.devstats.cncf.io/d/39/sig-issues?orgId=1 (redirects to new) 
- New link: https://k8s.devstats.cncf.io/d/39/issues-opened-closed-by-sig?orgId=1

**Comment by lukaszgryglicki** [comment]
Done. Let me know if I can close this.

**Comment by jberkus** [comment]
Looks good, thanks!
