### ISSUE TITLE
Data loss for PRs is more severe than for Issues

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#113]
Lukasz,

So I was trying to use the database to run some reports on PRs in 1.11.  However, according to the database we have 160 open PRs (and 38 closed ones).  In reality, we have 41 open PRs (and 127 closed ones).

It seems like *most* of the time, close events aren't getting through, and a lot of change milestones aren't either.

**Comment by dankohn** [comment]
If you put together a really clear set of examples, we can escalate this to
Sam Lambert at GitHub to get it extra attention.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Can you please put examples that you have find?
I'll tripple check on my side to be sure that events are missing on GHA side.

**Comment by lukaszgryglicki** [comment]
Needed to create really smart algorithm to hanlde rate limits/abuse - still testing it under very heavy multi-sync per hour load.
Created adaptive algorithm (it adjusts number of threads calling GitHub API and wait time when abuse/API limit reached), will be run for tests untill tomorrow on the test server.
It uses GitHub Repo/Issue events API instead of checkign issues that were recently updated using Issues API.
This is a total rewrite of `ghapi2db` tool, will see tomorrow how it works. I expect that it will make all our problems go away :-)

See:
- https://github.com/cncf/devstats/blob/master/cmd/ghapi2db/ghapi2db.go
- https://github.com/cncf/devstats/blob/master/ghapi.go

It should also correctly hanlde all edge cases. POC was written yesterday and it worked.
Today I've connected it to the default workflow and it seems to work.
The only issue is to see how it deal with limited GitHub API resources and adapts dynamically to situation. It also should not hang sync process for too long.

Main idea is that we're for each CNCF project getting:
- List of repos that were modified recently (all repos that had any issue changed during last 24 hours).
- Then we're calling get issues events for every such repos.
- We are paging issues untill we get issues older than 2 hours.
- For each of those issues (actually issue events) we're checking if we have such event in our DB
- If not - we're adding full issue state from this event (issue, milestone, labels, state, closed date etc etc)
- If we have such event - we're checing if we have a correct state. If not we're updating.
- Additionally after every hour (which sync starts at X:08) we can have missing events from, X:00 to X:08, that are not yet there because there is no GHA hours JSON yet. So every new hour we can create events that will (at least most of them() appear during the next sync. So we need a cleanup process that checks if we don't have too much artificial events. This is done too.
- There are a lot more small details, please see the sources if you are interested in them.

**Comment by lukaszgryglicki** [comment]
PR case **should** also be handled - I'll see how it works tomorrow.
Let's continue discussion [here](https://github.com/cncf/devstats/issues/111), closing this as a duplicate.
