### ISSUE TITLE
req: issue age dashboard

### ISSUE THREAD

**Issue by spiffxp** [cncf/devstats.archive#14]
It would be nice to have an issues-age dashboard, parallel to the [prs-age](https://devstats.k8s.io/dashboard/db/prs-age) dashboard currently in place

It would be nice, if possible, to be able to filter by: kind, sig, priority

The question I'm trying to answer is: how many auto-filed issues (author:k8s-merge-robot,label:kind/flake,"Failure cluster") have been addressed by humans vs. left untouched?

**Comment by lukaszgryglicki** [comment]
I will take a look on this when I'm back from OSS Prague.

**Comment by lukaszgryglicki** [comment]
I will implement full requested functionality so it will be a dashboard similar to PRs age but it will additionally contain drop-downs for:
- Kind (including "All" option)
- SIG (including "All" option)
- Priority (including "All" option)
Standard dropdowns are Period and Repository Group.

Some of those drop-downs are not yet used anywhere, and this is a quite complex view so ETA is about 2-3 days work.

**Comment by lukaszgryglicki** [comment]
I've created the first preview, only on https://cncftest.io atm.
It is missing documentation, test coverage etc.
I've created it for preview and to get eventual feedback during the weekend.
It measures the number of issues that are already closed and were opened in a given date range (like in previous weeks when Period=week selected). 
Those issues could be closed anytime not only during the aggregation period.

This is different that for PRs age dashboard - it measures time from open to merge, but if PR is still open, we treat its age as from opened to now.
Why?
Because if I do the same for issues (so include non-yet-closed issues in calculation and treat their age as from open to now) the median is ridiculously high, about 1200 hours which is 50+ days.
Maybe I could get some feedback on this?

Dashboard shows number and median time to close issue.
Allows to choose:
- aggregation period
- repository group
- sig
- kind
- priority

https://cncftest.io/dashboard/db/issues-age?orgId=1
![screen shot 2017-10-27 at 16 42 21](https://user-images.githubusercontent.com/2469783/32109737-d3c9bb9a-bb35-11e7-9305-96602afab4ee.png)

cc @dankohn

**Comment by lukaszgryglicki** [comment]
Now implemented in prod version: https://devstats.k8s.io/dashboard/db/issues-age?orgId=1

**Comment by spiffxp** [comment]
Thanks for putting this together so quickly.  I haven't had time to focus on operational metrics, this looks good for now.  The fact that including open issues blows the age out of the water is useful, but I can't presently think of where I would want to use that data over this data.
