### ISSUE TITLE
Export list of first-time contributors for a period

### ISSUE THREAD

**Issue by jpkrohling** [cncf/devstats.archive#150]
This is a feature request, based on this thread: https://twitter.com/jpkrohling/status/1057292924654895104

For the Jaeger monthly newsletter, we like to recognize all our first-time contributors since the last newsletter, which usually means listing all the first-time contributors for the month: https://medium.com/jaegertracing/october-2018-newsletter-22c47541b8b1

My feature request is then to have devstats to provide a way to export a list of such first-time contributors. A first-time contributor is someone who got a PR merged (ie, commit) and has never had any *commits* before in any of the repositories under the `jaegertracing` organization.

The following script is currently being used to generate the list seen in the newsletter and could be used as reference: https://github.com/jpkrohling/list-first-time-contributors

**Comment by lukaszgryglicki** [comment]
@dankohn  this is a feature request, it will require to make a new type of tabular view, that will show data for a period (from, to) selected from the date picker. I think this requires about 2 days to implement (possibly less). let me know if I can work on this.

**Comment by dankohn** [comment]
+1

**Comment by lukaszgryglicki** [comment]
OK thanks, will work on this.

**Comment by lukaszgryglicki** [comment]
So this should be based on PRs only? Or maybe use DevStats approach where contributor is defined as anyone who made:
- issue
- PR
- PR review
- commit
- issue comment
- commit comment
?

**Comment by lukaszgryglicki** [comment]
Will implement for PRs first (just like the linked article and code), but I can also implement this for contributors defined [above](
https://github.com/cncf/devstats/issues/150#issuecomment-436145835)

**Comment by jpkrohling** [comment]
For Jaeger's purpose, it's only *commit* (PR merged).

**Comment by lukaszgryglicki** [comment]
OK.

**Comment by lukaszgryglicki** [comment]
The dashboard is ready [here](https://jaeger.devstats.cncf.io/d/52/new-contributors-table). It required to add a new type of data (`custom_data`) to allow metrics that return time series with text data instead of floating point values.
You can select a single repository from the repository group drop-down or display summary for all repositories combined (repository group=All, this is the default).
You can select a date range to display new contributors from the top-right date picker (default is last month).
This is an example [report](https://jaeger.devstats.cncf.io/d/52/new-contributors-table?orgId=1&from=1530396000000&to=1533074400000) for July 2018 (just like in the article linked).

@dankohn I've also added this dashboard to all non-kubernetes projects, for example [envoy](https://envoy.devstats.cncf.io/d/52/new-contributors-table?orgId=1), [grpc](https://grpc.devstats.cncf.io/d/52/new-contributors-table?orgId=1), [prometheus](https://prometheus.devstats.cncf.io/d/52/new-contributors-table?orgId=1), All CNCF projects [combined](https://all.devstats.cncf.io/d/52/new-contributors-table?orgId=1) (which uses each CNCF project as a repo group, so you can see [Kubernetes](https://all.devstats.cncf.io/d/52/new-contributors-table?orgId=1&var-repogroup_name=Kubernetes) there) etc.

I'm formatting contributor name as:
- Name (github_id) - if name is present on the profile.
- github_id - if name is not present on the profile.

**Comment by lukaszgryglicki** [comment]
Closing.

**Comment by jpkrohling** [comment]
Thanks, @lukaszgryglicki ! I see some divergences for the month of October. Are you able to investigate why this is not matching? In the blog post, we see the following users as first-time contributors, but they are missing from the dashboard:

* Michael Puncel (@mpuncel)
* Annanay Agarwal (@annanay25)
* Andrew DiNunzio (@adinunzio84)

**Comment by lukaszgryglicki** [comment]
`mpuncel`: this user had a PR merged on September 19th, so this is not a first merged PR in October: https://github.com/jaegertracing/jaeger-client-go/pull/333
Checking the remaining ones.

**Comment by lukaszgryglicki** [comment]
For the third case, I don't see `adinunzio84` merged in my data-set. This may be due to the GHA issue, the PR is https://github.com/jaegertracing/jaeger-client-node/pull/305 (it is merged on GitHub but not merged in the data set coming from GHA).
Investigating 2nd case.

**Comment by lukaszgryglicki** [comment]
I have a bug for 2nd case, but this is a deeper bug, will take some time to fix it.

**Comment by lukaszgryglicki** [comment]
The case with `annanay25` (2nd case) is fixed. The 3rd case `adinunzio84` cannot be fixed in an easy way - report generates data from what is available from the data source, for this particular PR we're missing merge event (it happens rarely) so, unfortunately, I cannot fix this atm. The 1st case `mpuncel` is wrong in the article IMHO.

**Comment by jpkrohling** [comment]
> The 3rd case adinunzio84 cannot be fixed in an easy way - report generates data from what is available from the data source, for this particular PR we're missing merge event (it happens rarely) so, unfortunately, I cannot fix this atm

That's a bummer. This means then that I have to still rely on the existing script, as it's far better to recognize someone twice (mpuncel's case) than to not recognize someone due to a bug somewhere.

**Comment by lukaszgryglicki** [comment]
I will try to fix this but I have no ETA on this, because this also requires work on the GitHub archives side.

**Comment by lukaszgryglicki** [comment]
@jpkrohling fixed `adinunzio84` case manually: https://jaeger.devstats.cncf.io/d/52/new-contributors-table?orgId=1&from=1538344800000&to=1541026800000
