### ISSUE TITLE
Reviewers are hard-coded?

### ISSUE THREAD

**Issue by justinsb** [cncf/devstats.archive#154]
Looking at https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/pr-reviews-by-contributor.json#L392 , I see that the list of default reviewers is hard-coded.  Is there a reason for that?

**Comment by lukaszgryglicki** [comment]
They are not hardcoded. This is just a top 20 or 15 selected from the drop-down. Anybody can go to the dashboard and choose any list from a multi-select drop-down.

**Comment by justinsb** [comment]
There are clearly values in there though :-)

Where is the query that populates these values then?

**Comment by lukaszgryglicki** [comment]
Values are selected from the UI and then dashboard is saved as a JSON, that's why those values are in the JSON file. Drop-down values for all users are fetched using [this tags query](https://github.com/cncf/devstats/blob/master/metrics/shared/reviewers_tags.sql).
Tag is defined [here](https://github.com/cncf/devstats/blob/master/metrics/shared/tags.yaml#L24).
![screenshot 2018-11-09 at 16 49 57](https://user-images.githubusercontent.com/2469783/48272769-b7a64580-e43f-11e8-87b9-6976e6c183d9.png)
![screenshot 2018-11-09 at 16 50 05](https://user-images.githubusercontent.com/2469783/48272770-b7a64580-e43f-11e8-95a2-758818bdde68.png)
![screenshot 2018-11-09 at 16 50 19](https://user-images.githubusercontent.com/2469783/48272771-b83edc00-e43f-11e8-8531-037da745e5f6.png)

**Comment by justinsb** [comment]
It looks like that select statement is unordered?  Can we default to "all" or add an order clause?  My concern is that it gives the impression that these are the top N, but that doesn't appear to be the case.

**Comment by lukaszgryglicki** [comment]
Select is orderes (it has order by events clause), I cannot just select all, it changes all the time, so drop-down values are different everyday. I can select none if preselecting few is a problem. Anybody can actually select whatever he/she like from the drop down. Tags are updated once a day.

**Comment by justinsb** [comment]
OK, thank you.  I guess the numbers don't quite match what I'd expect, but I guess I'll just have to do a lot more reviews and see if I pop up there :-)

**Comment by justinsb** [comment]
Ah - here's one - why doesn't andrewsykim appear here: https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d&var-repo_name=kubernetes%2Fkops&var-reviewers=All

He lgtm-ed this PR, for example: https://github.com/kubernetes/kops/pull/5981

**Comment by lukaszgryglicki** [comment]
It displays top N reviewers, it is impossible to show all of them - drop-down will have hundreds or even thousands of reviewers then.

**Comment by lukaszgryglicki** [comment]
Closing, feel free to reopen if needed.
