### ISSUE TITLE
Exporting data

### ISSUE THREAD

**Issue by duglin** [cncf/devstats.archive#157]
Perhaps I'm just not seeing it, but is there a way to export the results of the dashboards so that people can programmatically get the data? For example, I would love to be able to (via a program), grab the results (the raw data) of this dashboard: https://cloudevents.devstats.cncf.io/d/9/developers-summary?orgId=1&var-period_name=Last%20month&var-metric=contributions  and reuse it in some of my other work.

**Comment by lukaszgryglicki** [comment]
Click on the panel header, then "More -> Export CSV".
This is documented [here](https://github.com/cncf/devstats/blob/master/EXPORT.md)
![screenshot 2018-11-28 at 07 01 42](https://user-images.githubusercontent.com/2469783/49132249-c0ba6200-f2db-11e8-8cf2-5ca16622c793.png)
And this is a dashboard exported to CSV (saved with txt extension because GitHub forbids CSV): [grafana_data_export.txt](https://github.com/cncf/devstats/files/2623107/grafana_data_export.txt)

**Comment by duglin** [comment]
oh neat thanks!  Is it possible to get that data/csv via a curl cmd rather than thru the browser?

**Comment by lukaszgryglicki** [comment]
There is no curl interface, but you can create a feature request for this. Not sure if Grafana has anything like that (I think it hasn't) and all I could possibly do would be to create some *endpoint* that would return full data that is used to generate a dashboard.
But please note that it would have to be an additional API because you will have to pass all params from the browser like data range, drop-down selected values etc. That will be a big task.
cc @dankohn

**Comment by duglin** [comment]
ok thanks for the info. I'm not looking for you to do more work, was just hoping there was an existing API available to call, but if not I'll survive.  Thanks.

**Comment by lukaszgryglicki** [comment]
No problem. I would be happy to create API to allow downloading raw data but this would require some research and some decisions about output format (can be CSV, TXT, JSON, YAML, ...) and input parameters (like which project? which dashboard? date range? drop-down values?).
