### ISSUE TITLE
Individual Project Health Dashboard

### ISSUE THREAD

**Issue by nwoods3** [cncf/devstats.archive#159]
Feature request: 

The Project Health Dashboard is very well done and valuable information: https://all.devstats.cncf.io/d/53/projects-health?orgId=1

For the quarterly individual project velocity reports it would be nice to show maintainers their individual project health in a similar dashboard vs the whole dashboard. Anyway to create this for the January reports? Please.

**Comment by lukaszgryglicki** [comment]
Not sure what do you mean... Just show a single column for a single project?

**Comment by nwoods3** [comment]
Yes, a way to only show one project vs all. Thank you

**Comment by lukaszgryglicki** [comment]
Shouldn't be difficult, will think about something.
You want this on the [all.devstats.cncf.io](http://all.devstats.cncf.io) page, right? Possibly just the same URL but with some drop-down allowing to choose all any specific projects + All options?

**Comment by lukaszgryglicki** [comment]
I've implemented the new dashboard that reuses existing Projects health data.
It uses plain Grafana table instead of dynamically generated HTML with all projects.
You can select any CNCF project from the drop-down and it will show a table metric + value for the selected project:
https://all.devstats.cncf.io/d/54/project-health?orgId=1
Project name can be included in stateful URL, for example for gRPC: https://all.devstats.cncf.io/d/54/project-health?orgId=1&var-repogroup_name=gRPC
Original projects health dashboard untouched: https://all.devstats.cncf.io/d/53/projects-health?orgId=1.
The table looks slightly different because it is now Grafana native table, not a custom HTML, I don't have many options to change that view.

**Comment by lukaszgryglicki** [comment]
Closing this, please reopen if needed.
