### ISSUE TITLE
Feature request to track PR velocity stats by kind label

### ISSUE THREAD

**Issue by liggitt** [cncf/devstats.archive#163]
This is a feature request to get more granularity around these PR velocity stats:
* https://k8s.devstats.cncf.io/d/14/pr-time-to-engagment?orgId=1
* https://k8s.devstats.cncf.io/d/25/open-pr-age-by-repository-group?orgId=1
* https://k8s.devstats.cncf.io/d/44/pr-time-to-approve-and-merge?orgId=1

Being able to see velocity over time for different `kind/*` labels of PRs would be very useful (I have these kinds in mind specifically, but others might be interested in other kinds as well)
* kind/bug
* kind/feature
* kind/design
* kind/api-change

**Comment by lukaszgryglicki** [comment]
Will check what I can do tomorrow. Thanks for a feature request.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
With `PR time to engagement` the problem is that it calculates the time to first non-author activity. This is very often a `/label kind/xyz` comment. Say it happens 5 mins after issue creation. Then we don't have that label on the issue yet. Bot adds this label after this comment. I'll struggle a little more with this, but I think adding this to that dashboard can be very inaccurate.

**Comment by lukaszgryglicki** [comment]
Reviewed many PRs on k/k and /kind is usually set when creating PRs, so possibly it will be OK. This is a bit different with issues and possibly other repos, anyway - there will be `All` value that will keep the current state and then `kind/*` labels to choose, but we need that label to be set since the real beginning which will probably cover most cases at least with `k/k` repo.

**Comment by lukaszgryglicki** [comment]
- PR time to engagement first preview (on the test server): [click](
https://k8s.teststats.cncf.io/d/14/pr-time-to-engagment?orgId=1)

**Comment by lukaszgryglicki** [comment]
Added `kind` filter on 3 dashboards on both test and prod servers:
- [PR time to engagment](https://k8s.devstats.cncf.io/d/14/pr-time-to-engagment?orgId=1)
- [Open PRs age by repo groups](https://k8s.devstats.cncf.io/d/25/open-pr-age-by-repository-group?orgId=1)
- [PRs time to approve & merge](https://k8s.devstats.cncf.io/d/44/pr-time-to-approve-and-merge?orgId=1)

@liggitt Let me know if you have any feedback.

**Comment by lukaszgryglicki** [comment]
No more feedback received, closing.
