### ISSUE TITLE
separate out operations scripts for cncf projects into a separate devstats-ops repo

### ISSUE THREAD

**Issue by kapilt** [cncf/devstats.archive#165]
I was interested in trying out devstats, but the mix of tooling and operations with the source code, many installation steps involving dozens of interconnected shell scripts, makes its clear it feel like its all geared towards the singleton installation for cncf, rather then use as a general purpose tool. Ideally to be more tool oriented would moving the cncf instance operations to a separate repo from the code, and then also cleaning up and unifying some of the install shell scripts. Just curious if there is interest around this.

**Comment by dankohn** [comment]
I think like nearly all projects, DevStats began as a desire to scratch some specific itches CNCF has been dealing with. 

That said, we would be happy to accept PRs to generalize it so that it works well for other projects and that onboarding is easier.

**Comment by lukaszgryglicki** [comment]
There already is a separate repo [devstats-example](https://github.com/cncf/devstats-example) which contains something like a "source-code only" (but using this repo to get actual devstats toolset) + one example deployment of a single project (Homebrew). There is also a [request](https://github.com/cncf/devstats-example/issues/6) to add a tool that will allow it to customize a new project with a single shell script call. This repo is a full devstats deployment for the CNCF projects, including all tools to create a full working stack with Apache proxy, Grafana, Let's encrypt certificates etc. Maybe we should consider renaming this repo to something like `devstats-cncf-deployment` and renaming `devstats-example` to just `devstats`.
I think this should be discussed by more people.

**Comment by dankohn** [comment]
We recently refactored the CNCF Interactive [Landscape](https://landscape.cncf.io) so that all of the code is in the upstream repo https://github.com/cncf/landscapeapp and https://github.com/cncf/landscape just contains the data and images. This allowed us to support the LFDL [Landscape](https://landscape.lfll.io) out of its own downstream repo https://github.com/LFDLFoundation/lfdl-landscape.

The same pattern might be appropriate for DevStats.

**Comment by kapilt** [comment]
i'm a bit reluctant to comment further only because i think i've decided to go my own path on scratching this itch, but a few more thoughts in that the hopes that its helpful. Currently the repos are

  - devstats (go code, shell scripts, cncf project configs)
  - devstats-example ( shell scripts, json/yaml for homebrew) 

I'd suggest separating the code in the devstats repo from the configuration around a particular installation, the code currently lives in this repo co-mingled with cncf deployment config which results in a fair bit of indirection. So effectively three repos (devstats, devstats-example, devstats-cncf), alternatively put the example as a subdir in the source repo. A more minimal alternative would be at least moving the cncf configs to a subdirectory in this repo. Alot of garnering contributions is simply making the code easier to read and comprehend to others to enable incremental safe changes. The devstats-example repo currently consists of 49 shell scripts, one of which copies 20 go binaries, from this repo, i'm not sure it really qualifies as a source repo for someone wanting to make a change. Its more a configuration repo example. Additionally the use of 50+ environment variables to config across many binaries, might be better serviced by having a config file. I think the over reliance on interlinked shell scripts without error handling or tests detracts from the abilities for others to get involved. The question is more about how to test a change or contrib, and while thats certainly possible in shell, the current structure makes that feel quite a bit brittle for those lacking full context for all the different parameter and extant usages. While a master shell script may help a user to get started (and i see one was committed in the last few hours for devstats-example), i'm not sure it really addresses the issue for contributions/changes.

**Comment by lukaszgryglicki** [comment]
I will work on this in the near future, one thing: configuration files were deliberately skipped in favor of environmental variables because it is easier to configure everything via setting environment variables in a script and they propagate to the other binaries being called, this also allows creating very custom docker/k8s configurations by just passing the correct set of environmental variables. Splitting this repo into 3 different repositories with just a toolset, CNCF deployment and example deployment is a very good idea IMHO. The current state is just an evolution of a simple project that finally supports tracking 30+ different projects and hundreds of repositories.

**Comment by lukaszgryglicki** [comment]
`devstats` and `devstats-example` will be split into multiple parts, at least such:
- code
- bare metal deployment for the CNCF projects
- kubernetes deployment for the LF
- docker deployments
- kubernetes deployment
- helm chart
- example deployment on bare metal

Maybe more or less.

**Comment by lukaszgryglicki** [comment]
I'm in progress of splitting code out of devstats (not modifying original devstats repo yet):
- Code split [here](https://github.com/cncf/devstatscode). It includes test coverage but without testing metrics. That will be present in the deployment repo. Documentation for the new code repo is minimal now because I don't know yet what the final structure will be.
- Made [devstats-example](https://github.com/cncf/devstats-example) able to use `devstatscode` repo as a source of binaries. So you first install `devstatscode` then customize your `devstats-example` for your project and install all. Updated documentation.
- Next, I'll remove code from the main repo, so it will contain different deployments (all of them).
- Next, I'll separate every possible deployment type into a separate repo.
- The CNCF [deployment](https://devstats.cncf.io) will remain in the original `devstats` repo.
- `devstatscode` + `devstats-minimal` together make an example bare metal deployment.
 - For all other deployments type, the correct approach will be `devstatscode` + `devstats-deployment-type` and for deployments that do not require `devstats` to be installed on the host (like K8s deployment or docker) approach will be `devstats-deployment-type` + `devstats-image-repo`.

So there will be a code repo, example and real deployments, images.

**Comment by lukaszgryglicki** [comment]
So the current (very wip) state is:
- [DevStats bare metal deployment + tests for all metrics](https://github.com/cncf/devstats). It is a deployment of:
- - [DevStats CNCF production](https://devstats.cncf.io)
- - [DevStats CNCF test](https://teststats.cncf.io)
- - [DevStats CDF production](https://devstats.cd.foundation)
- [Shared DevStats go code + tests](https://github.com/cncf/devstatscode).
- [DevStats docker images](https://github.com/cncf/devstats-docker-images):
- - `devstats` (full provisioning/bootstrap image).
- - `devstats-minimal` (image used by hourly sync k8s cron jobs)
- - `devstats-grafana` (Used by K8s Grafana UI endpoints).
- [Pure docker and/or vagrant deployment for LF projects](https://github.com/cncf/devstats-docker-lf).
- [Helm Chart for DevStats K8s deployment used by the LF](https://github.com/cncf/devstats-helm-lf).
- [Bare kubernrtes deployment + utility tools for a deployed K8s DevStats](https://github.com/cncf/devstats-k8s-lf). This one iw `wip`, see `TODO:` in README.md.
- [Example bare metal deployment](https://github.com/cncf/devstats-example). It only requires `devstatscode`. It contains instructions how to deploy own project via single script call.
- [Helm chart for json2hat tool](https://github.com/cncf/json2hat). It creates a k8s cronjob that periodically import newest `cncf/devstats` affiliations data into the GrimoireLab Perceval SortingHat database (MariaDB).

**Comment by lukaszgryglicki** [comment]
OK, all possible deployment split out from `cncf/devstats`. There will also be a new repo with a public kubernetes deployment, something like `cncf/devstats-helm-example`. This will be used for my and @jberkus [talk on KubeCon Barcelona](https://kccnceu19.sched.com/event/MPZG).
