### ISSUE TITLE
[bug] issue count includes PRs

### ISSUE THREAD

**Issue by BenTheElder** [cncf/devstats.archive#171]
This appears to be a straight forward case of using the GitHub V3 API which includes PRs in the issue endpoints. They can be filtered client side or the V4 API can give issues specifically.

Example: compare the numbers here and the repo
https://k8s.devstats.cncf.io/d/7/stars-and-forks-by-repository?orgId=1&var-period=d7&var-repo_name=kubernetes-sigs%2Fkind

**Comment by lukaszgryglicki** [comment]
No, this report uses [this metric](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/watchers.sql). It is not counting open issues in any way. It is just taking max from `forkee` structure instead. This means that GitHub returns the wrong value.
The only way to fix it would be to replace that SQL with a different query that really counts open issues instead of using a ready value provided by GitHub (which BTW seems to be the number of open PRs + number of open issues indeed).
We're not even using GitHub API, we're using GitHub archives that store a past state of all GitHub objects. I'll try to fix that by using another approach to get that data (manually count issues that were in the opened state during the requested period).

**Comment by BenTheElder** [comment]
> instead of using a ready value provided by GitHub (which BTW seems to be the number of open PRs + number of open issues indeed).

In GitHub's v3 API PRs are Issues, this is well known and documented.

https://developer.github.com/v3/issues/

> Note: GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key.
>
> Be aware that the id of a pull request returned from "Issues" endpoints will be an issue id. To find out the pull request id, use the "List pull requests" endpoint.

In V4 they are not.

**Comment by lukaszgryglicki** [comment]
Yes, I know that. But this won't help because I'm not using GitHub API. I'm using GitHub archives, which contains all GitHub data back to 2012. I cannot use any v3 or v4 API here, but I can just count all issues that are not PRs. This is handled in many other dashboards, the only problem here is that it is using a ready value instead of calculating this.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
So because this metric value is wrong (misleading) I'll rename it to "Open Issues and PRs". I was just about to add "Open Issues" metric but we already have that metric in another dashboard: [Open issues/PRs by milestone and repository](https://k8s.devstats.cncf.io/d/22/open-issues-prs-by-milestone-and-repository?orgId=1&var-sig_name=All&var-milestone_name=All&var-repo_name=kubernetes-sigs%2Fkind&from=now-6M&to=now). You just need to select `SIG=All`, `Milestone=All`, `Repository=kubernetes-sigs/kind`. I've manually checked values for Open PRs and Open Issues for this repository and they're the same as GitHub.
So I will only rename value shown on this dashboard and update documentation.

**Comment by lukaszgryglicki** [comment]
Updated charts everywhere (K8s and non-k8s projects on both test & prod servers). Closing. Please reopen if needed.
