### ISSUE TITLE
Increase size of OpenTracing logo

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#18]
Please make sure that You follow instructions from [CONTRIBUTING](https://github.com/cncf/devstats/blob/master/CONTRIBUTING.md)

Please increase the size or center the existing logo.

https://opentracing.devstats.cncf.io/dashboard/db/project-statistics?orgId=1&var-period=y10&var-repogroup_name=All&var-repogroup=all

**Comment by lukaszgryglicki** [comment]
Seems like the SVG file is not centered, I'll take a look when I finish other stuff.

**Comment by radoslaw** [comment]
no, widoczne jako 30x30
w oryginale 150x150 ale nie wyśrodkowane, ja bym zmienil canvas do 120x120 przy okazji
R
    On Friday, November 17, 2017, 12:46:26 PM GMT+1, Łukasz Gryglicki <notifications@github.com> wrote:  
 
 
Seems like the SVG file is not centered, I'll take a look when I finish other stuff.

**Comment by lukaszgryglicki** [comment]
This is a broken OpenTracing SVG file.
See this (GIMP):
![screen shot 2017-11-17 at 13 24 01](https://user-images.githubusercontent.com/2469783/32947148-c0614314-cb9a-11e7-8de5-dea6d5181a56.png)
![screen shot 2017-11-17 at 13 24 06](https://user-images.githubusercontent.com/2469783/32947149-c082806a-cb9a-11e7-8c82-a0b57e21cdbb.png)
![screen shot 2017-11-17 at 13 24 13](https://user-images.githubusercontent.com/2469783/32947150-c09cb584-cb9a-11e7-8a44-4bae77dbd6df.png)

Logos are taken from https://github.com/cncf/artwork
OpenTracing one used here is: https://github.com/cncf/artwork/blob/master/opentracing/icon/color/opentracing-icon-color.svg

I'll try to fix this locally, but this should also be fixed in the `cncf/artwork` repo too.

**Comment by dankohn** [comment]
Awesome. If you can fix, please open a PR on cncf/artwork. Otherwise, I can
have our designer, Alex, do it.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Created issue in the original repo. If I fix it I'll create PR.
https://github.com/cncf/artwork/issues/14

**Comment by lukaszgryglicki** [comment]
Fixed by: https://github.com/cncf/devstats/commit/d9161e995d169e6882d648b803c3ec0a63d044f2
I'll create PR in `cncf/artwork` now.
