### ISSUE TITLE
[Feature Request] Add additional time ranges to the Developer Activity Counts dashboard

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#196]
Dashboard: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1

Right now it is a bit difficult to track year-over-year trends with the current available selection of time ranges. Would it be possible to add a few more options such as `Last 2 Years` and `Last 3 Years`?

Thanks!

**Comment by lukaszgryglicki** [comment]
We can do that, but we can only have a fixed specific list of periods. Currently, we have "Last X" where X is a day, week, month, quarter, year, decade ... and then inter-release ranges like `v0.1 - v0.2`, `v0.2 - now`. Having this means we have to add a lot of data to the database (to store precalculated data).
cc @dankohn

**Comment by lukaszgryglicki** [comment]
Worked on this today,  I now have a [new SQL](https://github.com/cncf/devstats/blob/master/metrics/shared/watchers_by_alias.sql) that will generate correct data (tested internally). This SQL will replace [the old one](https://github.com/cncf/devstats/blob/master/metrics/shared/watchers.sql) which was much simpler and didn't support aggregating sums and avoiding data duplication.

I'll probably finish this tomorrow (Saturday) because it is very interesting to me, but if I don't do it during the weekend, I'll do it next week.

**Comment by mrbobbytables** [comment]
Awesome, thanks so much @lukaszgryglicki :)
