### ISSUE TITLE
[Feature Request] Additional metrics in "User Statistics" page

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#216]
The User Statistics page has a lot of interesting metrics, but it would be interesting if there were some additional ones.

Some ideas:
* PRs merged - right now there is just PRs opened, but PRs that they opened and were merged maybe be useful as well
* Issues closed (the user clicking close)
* PRs closed (the user clicking close)
* PRs approved (the user clicking approve)
* PRs with requested changes (the user clicking "request changes")

I don't have any specific need for these, just some ideas, so I wouldn't consider this high priority at all

**Comment by lukaszgryglicki** [comment]
I will take a look when I have time, thanks.

**Comment by lukaszgryglicki** [comment]
cc @dankohn should I implement this?

**Comment by dankohn** [comment]
@howardjohn one if the issues with DevStats is that it is already getting so large that it’s challenging to find the statistics you’re looking for. Since you don’t have an urgent need for these, I’m going to close the request for now. If you want to reopen in the future, I’d appreciate if you could raise first in the #devstats channel in K8s Slack.
