### ISSUE TITLE
[feature request] Add dashboard to filter by language/license

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#232]
I'd love to learn different license type usage across languages, primarily for:
https://devstats.coreinfrastructure.org/d/1/activity-repository-groups?orgId=1

My thesis is that MIT/BSD is more popular in Javascript than say GPL etc.

You can get license info via:

1) GitHub has a built into API for each repo: https://developer.github.com/v3/licenses/
2) https://github.com/licensee/licensee against a repo

**Comment by lukaszgryglicki** [comment]
New licenses dashboard created, this is how it looks like: 

- CII: https://devstats.coreinfrastructure.org/d/67/licenses?orgId=1 (MIT is by far the most popular in JS)
- All CNCF: https://all.devstats.cncf.io/d/67/licenses?orgId=1 (Apache 2.0 is dominant)
- CDF: https://allcdf.devstats.cd.foundation/d/67/licenses?orgId=1 (mostly no license and then MIT)

I didn't add this dashboard to Kubernetes DevStats because this requires community approval (cc @jberkus @spiffxp)

It's also added in all CNCF projects DevStats instances (excluding Kubernetes), for example, Prometheus: https://prometheus.devstats.cncf.io/d/67/licenses?orgId=1.

**Comment by lukaszgryglicki** [comment]
Will add programming language: https://developer.github.com/v3/repos/#list-languages, Single repo may have multiple languages according to that API.
Also need to add dashboard docs.

**Comment by lukaszgryglicki** [comment]
So here are dashboards with filtering by licenses, programming languages and repository groups:
- CII: https://devstats.coreinfrastructure.org/d/67/licenses-and-programming-languages
- All CNCF: https://all.devstats.cncf.io/d/67/licenses-and-programming-languages
- GraphQL: https://graphql.devstats.graphql.org/d/67/licenses-and-programming-languages
- CDF: https://allcdf.teststats.cncf.io/d/67/licenses-and-programming-languages
- CNCF itself: https://cncf.teststats.cncf.io/d/67/licenses-and-programming-languages

I didn't create that dashboard for Kubernetes project because it requires community approval (but added in all other projects). I've asked K8s community if they want it or not.
