### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by adamkane13** [cncf/devstats.archive#284]
Please add `[feature request]` to the issue title when requesting new features, dashboards, projects etc.
Please add `[bug]` to the issue title when reporting a bug.

Is there a way you can add company contribution totals to data like this? https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&from=1447338914018&to=1605191714018&var-period_name=v1.19.0%20-%20v1.20.0&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=VMware%20Inc.&var-companies=Pivotal

either at the top or at the bottom. The idea would be to compare different companies totals together and see which company is contributing more or less?

Also, is there a metric to traffic contributions of companies between each release? i.e. 1.19 vs 1.20 data to see increase vs decreases

**Comment by lukaszgryglicki** [comment]
Will try to see what I can do next week, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
I think I can't add totals here, because the companies drop-down is a multi-select, so there is no single total to be displayed there.
But you can just get all the data as a CSV file and then put it in some google sheet and manipulate it in any way you want.

To export data click on the panel header  "Kubernetes Developer statistics" - the drop-down menu will show up. Then choose "Inspect -> Data ->   Download CSV"

Example file attached: [dump.csv](https://github.com/cncf/devstats/files/6008042/dump.csv.txt)

**Comment by lukaszgryglicki** [comment]
Let me know if the data dump is enoght for you to get the data? I'll eventually reopen, but the feature as requested is hard to be implemented, see my previous post.

**Comment by adamkane13** [comment]
Awesome. Thank you. This is a good alternative I appreciate it
