### ISSUE TITLE
Custom Date Ranges for Dashboards

### ISSUE THREAD

**Issue by parispittman** [cncf/devstats.archive#29]
It would be helpful to be able to pick a custom date range for all dashboards. 

Use Case: We are creating programs around mentoring and contributor ladder where we will need to measure the value from multiple angles and the programs may not start or end on a specific 7 day/month/etc. period. It may be something like the last three days or two weeks, etc.

**Comment by lukaszgryglicki** [comment]
Well, we don't have that value computed for all possible periods, and can't do that on demand.
On "chart" dashboards You can see charts for given periods, but for tabular dashboards/histograms all values must be precomputed, and I have no way to guess which values would be needed.

Seems real hard, any ideas how to implement this?

**Comment by lukaszgryglicki** [comment]
I'm closing this, please reopen if needed.

**Comment by parispittman** [comment]
So there is no way for a calendar to be built in and then the user can filter by date ranges?

**Comment by dankohn** [comment]
If Lukasz doesn't have any other ideas he can open as issue with the Grafana team, link it here, and see what they suggest.

**Comment by lukaszgryglicki** [comment]
You can select a date range from the calendar for all chart dashboards. You can also select aggregation period day, week, moving average week, month etc.
For tabular dashboards, You can select any date range between releases, and last decade, year, quarter, month, 10 days, week, day.
What else do you need?

**Comment by dankohn** [comment]
She's asking for 2 arbitrary dates, right, Paris? Paris, could you please
give us an example of the kind of question you want to answer?

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Waiting for more feedback, but please note.
- Tabular dashboards currently include all date ranges between releases/tags, such tags are defined in the main [projects.yaml](https://github.com/cncf/devstats/blob/master/projects.yaml) file using `annotation_regexp` property. All releases/tags matching this report will be used to generate date ranges for tabular reports.
- Tabular dashboards also include a standard set of `Last X` periods, X being: day, week, 10 days, month, quarter, year, decade. We can't expect those tabular dashboards to include all possible date ranges, every date range must be known and computed periodically before being accessible to the end users.
- Chart dashboards have date range selector allowing to choose any date range from project beginning date to now (date selector is in the top right corner).
- Chart dashboard usually contains `Period` drop down that allows choosing "aggregation period", so every point (or bar) on the chart will show value aggregated over this period. So you can see previous aggregated periods here, usually, the list includes day, week, 7 days moving average, month, quarter, year etc. It is possible to define any other aggregation period here - but I need to know which periods are needed to add. For example, 10 Days moving average, etc.
- The most useful period seems to be 7 days MA because for example 10 days MA sometimes include 2 weekends and sometimes one - so data usually looks like a week pattern. 7 days MA always contain all possible 7 weekdays. We can also define 7 days moving sum etc. etc. I just need a list of periods needed for a particular dashboard.

**Comment by lukaszgryglicki** [comment]
I can only implement this by ceating custom Grafana.
Grafana guys are not interested in adding quick date ranges from annotations.
I would have to clone Grafana repo, implement this and then use in DevStats (and possibly update every next Grafana instance).
Have this working I can also create PR on Grafana repo, maybe they will accept this...
