### ISSUE TITLE
[feature request] API for getting key CNCF metrics

### ISSUE THREAD

**Issue by cjyabraham** [cncf/devstats.archive#290]
Could you create an API call where we can get the metrics used at the top of [cncf.io](https://www.cncf.io/):
- Number of contributors across all CNCF projects
- Number of contributions across all CNCF projects
- Number of lines of code in all CNCF projects

**Comment by lukaszgryglicki** [comment]
API implemented, you can call it like this:
`curl -s -H 'Content-Type: application/json' https://devstats.cncf.io/api/v1 -d'{"api":"SiteStats","payload":{"project":"all"}}'`
Response:
```
{"project":"all","db_name":"allprj","contributors":121239,"contributions":5833526,"boc":2022088602}
```

One note: I don't have LOC (lines of code) info, GitHub only gives BOC (bytes of code), so API is returning BOC instead of LOC.

As you can see there is a `project` parameter - when you specify `all` you will get stats for all CNCF projects combined (as requested), but you can also get stats for a particular project, just specify project=kubernetes or grpc or any other CNCF project.

**Comment by lukaszgryglicki** [comment]
Let me know if you need any other stats, everything that is present in DevStats can also be returned from an API call.

**Comment by cjyabraham** [comment]
Any idea where LOC is pulled from?  Where did 261M come from?

**Comment by lukaszgryglicki** [comment]
No, I don't know where it comes from, you can do some tricky assumption that a line of code usually has say 60 bytes or whatever, but in this case, I don't think it comes from DevStats.

**Comment by lukaszgryglicki** [comment]
See [here](https://docs.github.com/en/rest/reference/repos#list-languages):
```
Lists languages for the specified repository. The value shown for each language is the number of bytes of code written in that language.
```
`bytes of code` - I don't have anything else.

**Comment by lukaszgryglicki** [comment]
Closing this now, please reopen if you want some more metrics or if there is any other problem with this.
