### ISSUE TITLE
Adding multiple repo selection to PR Authors Dashboard

### ISSUE THREAD

**Issue by parispittman** [cncf/devstats.archive#30]
I'd like to see the capability to select multiple repositories to the PR Authors Dashboard. Only one at a time can be selected now.
https://devstats.k8s.io/dashboard/db/prs-authors?orgId=1

**Comment by lukaszgryglicki** [comment]
Should be done easily.
@dankohn about the priority of this?

**Comment by dankohn** [comment]
Yes, please prioritize these changes before adding dashboards to other
projects.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
OK.
I see one problem if we do stacked chart here (like for 3 repo groups selected).
Say repo group A has 3 authors, repo group B has 5 authors and repo group C has 10 authors.
It will sum up to 18 but.... one developer can be an actor in all of them. In reality number of distinct authors in those A, B, C groups can be anywhere from 10 to 18 ( max(A, B, C) <= # of authors <= sum(A, B, C).
So such a chart would be confusing.

That's why we don't have such chart atm.

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if needed but please also note my last comment.
