### ISSUE TITLE
[bug] help with historical data devstats query

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#312]
Hello, we need some help with a DevStats query.

We would like to see historical trend data for:

Stargazers
PR Reviewers
Issue Creators
Issue Commenters

The current values are visible here:

https://kyverno.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1

Seems like the data exists, but we are not able to build a query either via Grafana or via Curl, etc. (https://github.com/cncf/devstatscode/blob/master/API.md).

If we can get a sample of one such query, we can build the rest. Thanks!

**Comment by Mini256** [comment]
Stargazers:
https://kyverno.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1

**Comment by JimBugwadia** [comment]
This is great! Thanks @Mini256! As project maintainers, do we have have access to customize and save dashboards?

**Comment by Mini256** [comment]
> This is great! Thanks @Mini256! As project maintainers, do we have have access to customize and save dashboards?

You can export the customized dashboard in JSON format, add it to the [grafana/dashboards/kyverno](https://github.com/cncf/devstats/tree/master/grafana/dashboards/kyverno) directory and submit a Pull Request.

In fact, before you add a new dashboard about historical data, you need to define a new metric to calculate historical data, you need to refer to the documentation: https://github.com/cncf/devstats/blob/master/METRICS.md

**Comment by lukaszgryglicki** [comment]
@caniszczyk - do you mean you want me to implement a new API that can data from [this dashboard](https://kyverno.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1) but for any arbitrary data range (like it was [recently added](https://github.com/cncf/devstats/issues/309) for a different dashboard?

Or do you just want to download data from [this](https://kyverno.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1)? 

In the latter case click the header "Kyverno project statistics" (down arrow when you hover the mouse over the header) then: -> Inspect -> Data -> Download CSV.

If you want data from this dashboard for any arbitrary date range then I need to add a new API for this - please just confirm that you want me to add such an API. Note that the dashboadr you listed is a "tabular" view for some pre-defined date ranges (like Last X and between versions - DevStats is not able to calculate any arbitrary range, because there can be almost infinite number of possible date ranges. Maybe you just want a chart-type dashboard similar to the one you listed at the beginning. In such case we can choose one pariod (for example a week) and then draw a chart of all values you want in one-week intervals starting from given project's start date?

**Comment by lukaszgryglicki** [comment]
Closing this, please reopen if needed.
