### ISSUE TITLE
[bug] developer-activity-counts-by-companies for kubernetes/kubernetes 

### ISSUE THREAD

**Issue by dims** [cncf/devstats.archive#318]
pondering a bit at https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20quarter&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=VMware%20Inc. I don’t see the first 4 people active in https://github.com/kubernetes/kubernetes repository. could be a problem with what exactly i should be seeing there? (or how exactly i should be looking for data for just the main kubernetes repo?)

Essentially i need to distinguish between `kubernetes github org`, `kubernetes-sigs github org`, `kubernetes/kubernetes github repository` and `all kubernetes github orgs`

but at the very least, data/url just for kubernetes/kubernetes alone (the folks mentioned above are mostly working on CAPI in kubernetes-sigs/* repositories)

**Comment by lukaszgryglicki** [comment]
Not really get what the problem is. This [dashboard](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20quarter&var-metric=contributions&var-repogroup_name=Kubernetes&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=VMware%20Inc.) has two views:
- 1st view: Repository group one (the top table), for that view you choose the repository group from the `Repository group` drop-down (in your link this is `All` (see the URL part `var-repogroup_name=All` in your link, that means you are looking at most active contributors across the entire Kubernetes project).
- 2nd view: Reposiotry one (the 2nd table) - this one shows data regarding a repository chosen from `Repository` drop-down. You selected `k/k` there (see URL `repo_name=kubernetes%2Fkubernetes`), so it shows stats for `k/k`. See [help](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20quarter&var-metric=contributions&var-repogroup_name=Kubernetes&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=VMware%20Inc.&viewPanel=3) - explaining two panels and why we need them.

Also note that contributor is someone who:
- Created a commit.
- Created an issue.
- Created a PR.
- Commented on the issue, PR or commit.
- Made a review.

So the 2nd table will show contributors having most contributions in `k/k` repo, currently top 4 (VMware Inc., last quarter selected) they are:
- `dims`
- `neolit123`
- `MadhavJivrajani`
- `endocrimes`

Here I check the DB for their contributions (simplified query):
```
select
  sub.actor,
  sub.type,
  count(distinct sub.event_id) as n
from (
select
  dup_actor_login as actor,
  id as event_id,
  type
from
  gha_events
where
  type in (
      'PushEvent', 'PullRequestEvent', 'IssuesEvent',
      'CommitCommentEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent'
    )
  and dup_actor_login in (
    'dims', 'neolit123', 'MadhavJivrajani', 'endocrimes'
  )
  and created_at >= now() - '3 months'::interval
  and dup_repo_name = 'kubernetes/kubernetes'
union select
  dup_author_login as actor,
  event_id,
  'CommmitAuthored' as type
from
  gha_commits
where
  dup_author_login in (
    'dims', 'neolit123', 'MadhavJivrajani', 'endocrimes'
  )
  and dup_created_at >= now() - '3 months'::interval
  and dup_repo_name = 'kubernetes/kubernetes'
union select
  dup_committer_login as actor,
  event_id,
  'Commmitied' as type
from
  gha_commits
where
  dup_committer_login in (
    'dims', 'neolit123', 'MadhavJivrajani', 'endocrimes'
  )
  and dup_created_at >= now() - '3 months'::interval
  and dup_repo_name = 'kubernetes/kubernetes'
) sub
group by
  sub.actor,
  sub.type
order by
  n desc
;
```

Gives:
```
      actor      |             type              |  n  
-----------------+-------------------------------+-----
 dims            | IssueCommentEvent             | 413
 neolit123       | IssueCommentEvent             | 314
 MadhavJivrajani | IssueCommentEvent             | 117
 neolit123       | PullRequestReviewCommentEvent | 114
 endocrimes      | IssueCommentEvent             |  86
 dims            | PullRequestEvent              |  37
 endocrimes      | PullRequestReviewCommentEvent |  29
 dims            | PullRequestReviewCommentEvent |  27
 MadhavJivrajani | PullRequestReviewCommentEvent |   9
 dims            | IssuesEvent                   |   8
 MadhavJivrajani | PullRequestEvent              |   6
 dims            | CommmitAuthored               |   4
 neolit123       | PullRequestEvent              |   4
 neolit123       | IssuesEvent                   |   3
 endocrimes      | PullRequestEvent              |   2
 MadhavJivrajani | IssuesEvent                   |   2
 MadhavJivrajani | CommmitAuthored               |   1
 endocrimes      | CommmitAuthored               |   1
(18 rows)
```

Hope that helps.

**Comment by lukaszgryglicki** [comment]
If we remove last quarter and k/k conditions via:
```
  -- and dup_created_at >= now() - '3 months'::interval
  -- and dup_repo_name = 'kubernetes/kubernetes'
```
commenting them out everywhere, we get:
```
      actor      |             type              |   n   
-----------------+-------------------------------+-------
 dims            | IssueCommentEvent             | 20288
 neolit123       | IssueCommentEvent             | 16560
 neolit123       | PullRequestReviewCommentEvent |  6593
 dims            | PullRequestReviewCommentEvent |  2145
 dims            | PullRequestEvent              |  1647
 dims            | CommmitAuthored               |  1130
 neolit123       | PullRequestEvent              |   760
 neolit123       | IssuesEvent                   |   718
 neolit123       | CommmitAuthored               |   671
 dims            | Commmitied                    |   569
 MadhavJivrajani | IssueCommentEvent             |   522
 dims            | IssuesEvent                   |   464
 neolit123       | Commmitied                    |   252
 endocrimes      | IssueCommentEvent             |   150
 MadhavJivrajani | PullRequestReviewCommentEvent |    63
 endocrimes      | PullRequestReviewCommentEvent |    57
 dims            | PushEvent                     |    54
 MadhavJivrajani | CommmitAuthored               |    37
 MadhavJivrajani | PullRequestEvent              |    36
 MadhavJivrajani | IssuesEvent                   |    13
 neolit123       | CommitCommentEvent            |    10
 endocrimes      | PullRequestEvent              |    10
 endocrimes      | CommmitAuthored               |     9
 MadhavJivrajani | Commmitied                    |     9
 dims            | CommitCommentEvent            |     6
 endocrimes      | Commmitied                    |     3
 endocrimes      | IssuesEvent                   |     1
 neolit123       | PushEvent                     |     1
```

**Comment by dims** [comment]
my bad. i lost track of the `Repository Group` vs `Repository`. thanks for the explanations @lukaszgryglicki
