### ISSUE TITLE
[bug] Duplicated accounts on "Developer Activity Counts"

### ISSUE THREAD

**Issue by oomichi** [cncf/devstats.archive#328]
According to current https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=v1.23.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-repo_name=kubernetes%2Fkubernetes
there are duplicated accounts on the table.
For example, `oomichi`, `justaugustus` and `YuikoTakada` are there twice.

**Comment by lukaszgryglicki** [comment]
It's not a bug - there are two views in this dashboard - one is for selected "repository group" (1st panel), another is for selected "repository" (2nd panel) - at the beginning, there was just one panel for repository groups, but then, there was a feature request to add a separate view where you can select single repositories instead of repository group - this is the second panel.
Check the documentation panel (3rd, the bottom one), saying:
```
You can select single repository group or summary for all of them (for the top panel).
You can select repository for bottom panel showing per single repository statistics.
```

**Comment by oomichi** [comment]
Ah, I got it.
Thanks for your explanation, @lukaszgryglicki
