### ISSUE TITLE
[bug] Incorrect number of commits in last 3 months for Meshery

### ISSUE THREAD

**Issue by debo19** [cncf/devstats.archive#330]
Ref: https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Meshery

I was looking at some of our stats and I think for some reason we don't see the expected data for Meshery.

- Incorrect last date of commit.
- A missing record of total commits made in the last 3 to 4 months.

**Comment by leecalcote** [comment]
This page shows data missing since July - https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1 (6 months). @lukaszgryglicki, is this due to a redirect from the old org (github.com) to the new org (gitHub.com/meshery)?

The statistics for the Meshery project will include all repos in the org, right? Not just the meshery/meshery repo.

**Comment by lukaszgryglicki** [comment]
Will check this and fix this when I can, I'm a bit busy this week, adding this to my TODO list.

**Comment by lukaszgryglicki** [comment]
Actually will check now, because I'm adding a new project and must regenerate `All CNCF` stats anyway.

**Comment by leecalcote** [comment]
Excellent timing. 😄

**Comment by lukaszgryglicki** [comment]
It's not yet fixed, but it's in progress "regenerating All CNCF". :p

**Comment by lukaszgryglicki** [comment]
Fixed.
