### ISSUE TITLE
[feature request] - adding ingress-nginx as a project to devstats

### ISSUE THREAD

**Issue by strongjz** [cncf/devstats.archive#349]
We would like to add https://github.com/kubernetes/ingress-nginx to the dashboard so that we as maintainers can discuss and understand who what and where contributions are coming from.

**Comment by lukaszgryglicki** [comment]
To which project? Kubernetes? We have 120+ projects.

**Comment by lukaszgryglicki** [comment]
Ping.

**Comment by strongjz** [comment]
Ingress-nginx is a subproject of Kubernetes, so I am not sure what you are asking here. 

To add the ingress-nginx project, do we follow this? https://github.com/cncf/devstats/blob/master/ADDING_NEW_PROJECT.md

**Comment by lukaszgryglicki** [comment]
OK so you want to add `https://github.com/kubernetes/ingress-nginx` repo, but to which CNCF project?
If kubernetes - then it is already tracked in https://k8s.devstats.cncf.io...

**Comment by lukaszgryglicki** [comment]
And if You want to add a new project (new DevStats instance) as described in [ADDING_NEW_PROJECT.md](https://github.com/cncf/devstats/blob/master/ADDING_NEW_PROJECT.md) - we are only adding CNCF projects, not just repos on user's requests cc @caniszczyk ?

**Comment by strongjz** [comment]
It's fine to add under kubernetes. I don't see ingress-nginx.

**Comment by lukaszgryglicki** [comment]
OK, I will check when I have some time.

**Comment by lukaszgryglicki** [comment]
I can see it in database:
```
gha=# select * from gha_repos where alias like '%ingress-nginx%';
    id    |           name           |  org_id  | org_login  | repo_group  |          alias           | license_key |    license_name    | license_prob |         created_at         |         updated_at         
----------+--------------------------+----------+------------+-------------+--------------------------+-------------+--------------------+--------------+----------------------------+----------------------------
 72891330 | kubernetes/ingress-nginx | 13629408 | kubernetes | SIG Network | kubernetes/ingress-nginx | apache-2.0  | Apache License 2.0 |          100 | 2020-02-13 07:38:59.026721 | 2021-09-06 02:02:00.150865
 72891330 | kubernetes/ingress       | 13629408 | kubernetes | SIG Network | kubernetes/ingress-nginx | apache-2.0  | Apache License 2.0 |          100 | 2020-02-13 07:38:59.026721 | 2021-09-06 02:02:00.213849
(2 rows)

gha=# 
```
It has two names `kubernetes/ingress-nginx` and `kubernetes/ingress` which means repo was renamed. Now on which dashboard you miss that repo? Note that some dashboards only show top N max active repos, not all.

If any dashboard shows "repository groups" it means that "ingress-nginx" will show as a part of "SIG Network" because it is listed in SIG Network repository group definition here: https://github.com/cncf/devstats/blob/master/scripts/kubernetes/repo_groups.sql#L265 and here https://github.com/cncf/devstats/blob/master/scripts/kubernetes/repo_groups.sql#L267, also see Dashboard for repository groups assignments: https://k8s.devstats.cncf.io/d/68/repository-groups?orgId=1&var-repogroups=SIG%20Network.

There are only few dashbaords that show data for "repositories" alone not "repositoriy groups", for example:
- https://k8s.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1&var-repo_name=kubernetes-sigs%2Fscheduler-plugins
- Bottom chart allows selecting individual repos: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fingress-nginx&var-country_name=All
- https://k8s.devstats.cncf.io/d/49/github-stats-by-repository?orgId=1&var-period=h24&var-repos=%22kubernetes%2Fingress-nginx%22&var-stat=reviewers

To have all dashboards that use "repository groups" distinguish that single repo you would have to split it out from "SIG Network" into its own 1-repository "repo group".

Hope that amnswers your question.

**Comment by lukaszgryglicki** [comment]
Closing this, please reopen if needed.
