### ISSUE TITLE
Add support for /lifecycle bot-command

### ISSUE THREAD

**Issue by spiffxp** [cncf/devstats.archive#40]
OK this one should be easy :)

A new bot-command /lifecycle was added within the last month or so, and is being used quite a bit.  I'd like to see that reflected in the bot-commands dashboard.

I was going to try PR'ing this myself but I'm not sure if I understand the development flow, my guess was I'd need to modify:
- metrics/kubernetes/bot_commands.sql
- metrics/kubernetes/bot_commands_tags.sql
- metrics/kubernetes/gaps.yaml

If I've got an example to follow I may be able to do this for other bot commands we may have missed

**Comment by lukaszgryglicki** [comment]
I will add this command in a single PR and send commit SHA to you, so you can see what needs to be done.
There is also a data regenerate part on the server side.

**Comment by lukaszgryglicki** [comment]
So I've created a separate branch (from `production` because `master` is now in wip state) with necessary changes:
https://github.com/cncf/devstats/tree/add-lifecycle-bot-command

To see changes: 
https://github.com/cncf/devstats/compare/production...add-lifecycle-bot-command (this will now show nothing because all of this is already merged, so please see direct commit link)

Or directly see commit:
https://github.com/cncf/devstats/commit/145fbe37811b146ad7691ff68a69726cadf55ba9

When you make that changes you need to:
- `crontab -e` and disable automatic sync (for a time to regenerate this single metric's data)
- `GHA2DB_PROJECT=kubernetes PG_PASS=... IDB_PASS=... IDB_HOST=... PG_DB=gha IDB_DB=gha ./devel/add_single_metric.sh`
- `crontab -e` to reenable automatic sync.

`./devel/add_single_metric.sh` script uses 3 yaml files `devel/test_metrics.yaml`, `devel/test_gaps.yaml` and `devel/test_tags.yaml`.
Those 3 files mitigate `metrics/kubernetes/metrics.yaml`, `metrics/kubernetes/gaps.yaml` and `metrics/kubernetes/idb_tags.yaml` but only contain "bot-commands" related data.

So the effect is regenerating series for this single metrics and this is why those 3 YAMLs also got modified for this task.

Works on the test and prod.

![screen shot 2018-01-03 at 08 17 05](https://user-images.githubusercontent.com/2469783/34511848-ae07100c-f05e-11e7-85c1-3d3b5c238b92.png)
![screen shot 2018-01-03 at 08 17 26](https://user-images.githubusercontent.com/2469783/34511849-ae234a2e-f05e-11e7-9e2a-6a7db187559d.png)
![screen shot 2018-01-03 at 08 17 43](https://user-images.githubusercontent.com/2469783/34511850-ae3dd3b2-f05e-11e7-909b-120b8dc46718.png)

**Comment by lukaszgryglicki** [comment]
Closing - implemented, but let me know if you want to reopen.

**Comment by spiffxp** [comment]
Again, thanks, this was very helpful

**Comment by lukaszgryglicki** [comment]
Anytime :)
