### ISSUE TITLE
Approver numbers for k8s dropped sharply

### ISSUE THREAD

**Issue by castrojo** [cncf/devstats.archive#44]
There's no description but assuming this chart is tracking the number of active reviewers (and not number of reviews done): 

https://k8s.devstats.cncf.io/dashboard/db/approvers?orgId=1&var-period=q&var-repogroups=All

Kubernetes went from around 100 approvers to 42, any insight on what happened here?

**Comment by lukaszgryglicki** [comment]
It does show number of distinct approvers in a given date period, see:
https://github.com/cncf/devstats/blob/master/metrics/kubernetes/approvers.sql#L12
But for the first quarter of 2018 only 17 days of about 90 passed.
It will be better to track 7 days MA (moving average) that shows the drop in the last few averages of the 2017 - but this is due to Holidays:
https://k8s.devstats.cncf.io/dashboard/db/approvers?orgId=1&var-period=d7&var-repogroups=All
You can also check monthly values, again December 2017 is smaller, but this is a general rule for all charts, January is also small but only 17 days of 31 passed so far:
https://k8s.devstats.cncf.io/dashboard/db/approvers?orgId=1&var-period=m&var-repogroups=All

**Comment by castrojo** [comment]
Ok, so if I'm an approver but I don't do anything in December then it wouldn't show up? 

I guess the real issue is the chart needs a description of what it's measuring, I was assuming it was just graphing the total number of approvers.

**Comment by lukaszgryglicki** [comment]
Yes, this is not an overall sum of all approvers, but rather sum of approvers that approved anything in a given "period" where period can be:
- Day
- Week
- 7 days MA (this is different than the week, a week is always Mon-Sun while 7 days MA is a "moving average" for 7 days: Mon-Sun, Tue-Sat, Wed-Fri etc.)
- Month
- Quarter
- Year
...

**Comment by castrojo** [comment]
Thanks for the clarification!
