### ISSUE TITLE
Combining dashboards

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#46]
Should we continue the work of #41 should we combine more dashboards?

Lukasz, on a dashboard like https://k8s.devstats.cncf.io/dashboard/db/companies-velocity?orgId=1 is it possible to add single line sections between each graph (like the please report section on the homepage) that would include an `A NAME` and so clicking on it would produce a URL like https://k8s.devstats.cncf.io/dashboard/db/companies-velocity?orgId=1#companies_active that would jump you to that section?

If so, shall we combine the three companies dashboards? Is there a logical order?

Can we combine the Issues and PRs dashboards?

The 4 SIGs ones?

Anything else?

@spiffxp @parispittman @castrojo Please chime in what you would find useful.

**Comment by lukaszgryglicki** [comment]
I would try to avoid combining more dashboards into one, please see that 'Companies velocity' is much slower than the other dashboards due to the big amount of data on this dashboard.
I'll research this task more (especially if this is possible to generate URL to a specific panel row) when I finish one piece of code (updating all metrics to use file-level granularity for repository groups definitions)
I'm somewhere about halfway done.

**Comment by parispittman** [comment]
I believe combining similar dashboards makes sense and will alleviate dashboard overkill for the casual user. Issues and PRs may want to stand alone and group them with others such as PRs (blocked, merged, authors) and Issues (time metrics, issue age, etc.).

It would be neat when combining dashboards that they line up so you could visually compare trends. The width on the legends is off here in this example which throws off the graphs.  (https://k8s.devstats.cncf.io/dashboard/db/prs-merged?orgId=1)

I really like the visual appeal of this (which may be a whole other issue itself) -> https://cncf.biterg.io/app/kibana#/dashboard/Overview?_g=()
I like how the dashboards are grouped on the left and then further filtration happens in each respective one.

**Comment by spiffxp** [comment]
[Companies Stats](https://k8s.devstats.cncf.io/dashboard/db/companies-stats?orgId=1) vs. [Companies Velocity](https://k8s.devstats.cncf.io/dashboard/db/companies-velocity?orgId=1&from=now-2y&to=now&var-period=w&var-repogroup_name=All&var-repogroup=all&var-companies=All) - these are the same data presented two different ways, I would keep one and drop the other... my preference would be keep stats and drop velocity:
- pro: stats lets you specify every parameter in the uri, you can link directly to a specific graph/query
- pro: stats displays a percentage-of-total graph
- bikeshed: I think I prefer the opaque bars from velocity instead of translucent stacked areas
- con: the panel descriptions need work
- con: I can't see all the different contribution types on one page for quick visual comparison

**Comment by spiffxp** [comment]
[Developers Summary](https://k8s.devstats.cncf.io/dashboard/db/developers-summary?orgId=1) could be fleshed out a bit to drop [Top Commenters](https://k8s.devstats.cncf.io/dashboard/db/top-commenters?orgId=1):
- add repository group as something to filter on
- allow "Metrics" dropdown to be a multi-select instead of single-select, aggregate into a total

**Comment by lukaszgryglicki** [comment]
I'm adding the remaining CNCF projects atm, so this will be postponed a bit.
But this is good IMHO - this needs some more discussion.

**Comment by jberkus** [comment]
We went through about 20 of the charts at yesterday's meeting, will forward notes shortly.

**Comment by jberkus** [comment]
We went through about 20 of the charts at yesterday's meeting, will forward notes shortly.

**Comment by lukaszgryglicki** [comment]
OK, waiting for feedback, and postponing documentation work, because I assume that there will be a lot of changes.

**Comment by lukaszgryglicki** [comment]
Some merging, deleting, updating work was done in different issues. Closing this.
