### ISSUE TITLE
Approvers and Reviewers histograms should have release milestone information

### ISSUE THREAD

**Issue by castrojo** [cncf/devstats.archive#49]
They seem to have a releases checkbox but for example I can't seem to find "who did the most reviews for 1.8". Am I looking in the right place?

**Comment by dankohn** [comment]
The releases checkbox just toggles whether releases are shown as dotted vertical lines.

Lukasz has implemented ranges on some dashboards like https://k8s.devstats.cncf.io/dashboard/db/companies-summary?orgId=1

It sounds like you want ranges on at least:

https://k8s.devstats.cncf.io/dashboard/db/approvers-histogram?orgId=1
https://k8s.devstats.cncf.io/dashboard/db/reviewers-histogram?orgId=1

as well.

Lukasz, would it make sense to implement ranges everywhere?

Also, I don't think `1.8.0-1.9.0` is actually what people want to see (though @castrojo should speak up here). I think you actually want `1.8.x`, meaning all 1.8 releases but not the 1.9.0. Or alternatively, you might prefer `post-1.8.0 to 1.9.0` meaning all commits after the 1.8.0 release up to the 1.9.0 release.

**Comment by lukaszgryglicki** [comment]
I'm open to suggestions - ranges are available in all tabular dashboards.
there are no ranges on charts because there is no way to see summary data. You can do something similar by selecting data range from Grafana UI on the top-right - You can select date range between release 1.8.0 and 1.9.0 (they are red vertical lines on the chart called "annotations")
Release names come from GitHub API.
Release names that are included are specified by `annotation_regexp` property in `projects.yaml` file.
ranges include all data between releases/tags returned by GitHub API:
https://github.com/cncf/devstats/blob/master/projects.yaml#L12

To see all data from 1.8 you should select 1.8.0 - 1.9.0 from the drop-down.

**Comment by lukaszgryglicki** [comment]
Approvers histogram for 1.8 --> 1.9:
https://k8s.devstats.cncf.io/dashboard/db/approvers-histogram?orgId=1&var-period_name=v1.8.0%20-%20v1.9.0&var-period=anno_28_29&var-repogroup_name=All&var-repogroup=all
Reviewers histogram doesn't have it on production yet, but it does have ranges drop-down on the test server atm:
https://k8s.cncftest.io/dashboard/db/reviewers-histogram?orgId=1&var-period_name=v1.8.0%20-%20v1.9.0&var-period=anno_28_29&var-repogroup_name=All&var-repogroup=all

**Comment by castrojo** [comment]
> Also, I don't think 1.8.0-1.9.0 is actually what people want to see (though @castrojo should speak up here). I think you actually want 1.8.x, meaning all 1.8 releases but not the 1.9.0. 

I would agree, it doesn't need to be that granular, I suspect we're using this graph to outline who has done a great job for a cycle and that usually entails it as a whole and not micro-releases.

**Comment by lukaszgryglicki** [comment]
Currently, the cron computes statistics between all releases:
And 1.8.0 - 1.9.0 is just a naming convention I've decided to use - but I can change to anything like:
- 1.8.0+
- 1.9.0
- from 1.8.0 to 1.9.0
- ...

It will be hard to change to just 1.8" or "1.9" - because I'm getting those tags from GitHub API.
For now, it seems easy just to strip ".0" but please take a look how complex those tags can be in general:
https://github.com/cncf/devstats/blob/master/projects.yaml
Look at the `annotation_regexp` property, for example:
https://github.com/cncf/devstats/blob/master/projects.yaml#L82

Or take a look at the other sites and their annotations:
*.devstats.cncf.io.

I can create any standard, but it must be well defined and applicable by some kind of transformation from a real GitHub tag/release.

**Comment by dankohn** [comment]
We could say `[1.8.0, 1.9.0)` but I don't think enough people would know what we meant to bother.

https://stackoverflow.com/a/4396303/1935918

**Comment by lukaszgryglicki** [comment]
Well for me this is obvious :)
I'm a big fan of math (especially I'm interested in tetration and other higher order operations beyond exponentiation): http://math.eretrandre.org/tetrationforum/member.php?action=profile&uid=226 :-)

BTW: I've just finished data regenerating of bot exclusion update: https://github.com/cncf/devstats/issues/48#issuecomment-359108141

**Comment by lukaszgryglicki** [comment]
Closing this now, we have custom ranges implemented long time ago and it allows to get infromations needed.
Please reopen if needed.
