### ISSUE TITLE
Min+max+avg in legends is a lie

### ISSUE THREAD

**Issue by bergquist** [cncf/devstats.archive#6]
If min+max+avg is enabled in the legend its important to know that the values are in fact the min/max/avg of the values returned from the query.

So if the query sent to Influxdb is aggregated by `avg()`
`min` will be the `min of the avg values` 
`max` will be the `max of the avg values` 
`avg` will be the correct value.

So the values might be off if you compare them to raw data.

**Comment by lukaszgryglicki** [comment]
Yes exactly, this is the min, max and avg of values from all periods.
Values for periods are calculated by Postgres, and InfluxDB only holds time series.
So we have max weekly value, min weekly value and avg weekly value (when weekly values can be anything).

**Comment by bergquist** [comment]
Ah. Sorry! I assumed you used influxdb for aggregations since that's what most people do :)
Your solution is correct

**Comment by lukaszgryglicki** [comment]
No, I use Postgres to do all calculations.
InfluxDB is only a time series data source.
This is why it is so fast!!
Postgres updates happen every hour from a cron job, and then it only adds few new values to Influx (since last hour).
Grafana only uses the simple `select value from series_name` so data retrieval is just a few ms.
