### ISSUE TITLE
Open Container Initiative

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#66]
Please create separate DevStats instances for the Open Container Initiative projects on *.devstats.opencontainers.org.

Please do 5 projects + all:
image-tools
image-spec
runtime-tools
runtime-spec
runc

Cc @caniszczyk

**Comment by lukaszgryglicki** [comment]
Not in our domains?
*.cncftest.io and *.devstats.cncf.io.
Who is going to configure those domains and point them to the test server and to the prod server?

What will be the final URLs?
- image-tools.devstats.opencontainers.org
- image-spec.devstats.opencontainers.org
-
...
- runc.devstats.opencontainers.org
- all.devstats.opencontainers.org
?

What will be the test URLs for them? Maybe on the current test server, something like?

- image-tools-opencontainers.cncftest.io or maybe (if allowed) image-tools.opencontainers.cncftest.io
...
- runc-imagetools.cncftest.io or runc.opencontainers.cncftest.io
- all-opencontainers.cncftest.io or all.opencontainers.cncftest.io
?

Should our current "All" on the test server include them too?
What is the priority?

Asking because I've found a way to get rid of gaps-config that will simplify DevStats a lot, and I wanted to implement this. I need one day for this.
How about this: https://github.com/cncf/devstats/issues/45 - higher or lower priority?

**Comment by lukaszgryglicki** [comment]
How about "Home" dashboard on those new projects?
Should it include only links between them (6 projects) or should it include a link (or links) to CNCF projects?
How about current "Home" dashboards for CNCF projects, should they include a link (or links) to open containers projects?
How about images, icons for those open containers projects? Where should I get them from?

And how about repositor lists for each of those projects?

Didn't you just list single repositories? If so then I'm thinking that single project like "opencontainers" will be enough, and all those repositories listed will just be "repository groups" under it?

**Comment by lukaszgryglicki** [comment]
@dankohn need your feedback here, please.

**Comment by lukaszgryglicki** [comment]
I think we don't need separate repos as "projects" here, see:
![screen shot 2018-02-08 at 07 06 12](https://user-images.githubusercontent.com/2469783/35957966-962ea0f6-0c9e-11e8-9799-17e40f2466c6.png)

DevStats is designed to work on projects that contain multiple repositories.
I would rather like to create single projects "opencontainers" and eventually limit it to the given "projects":
- image-tools
- image-spec
- runtime-tools
- runtime-spec
- runc

each of them would be defined as "repository group", just like each CNCF projects is defined as "repository group" on https://all.cncftest.io.

This is kind of blocked due to this.
I will implement something like https://opencontainers.cncftest.io or https://all.opencontainers.cncftest.io and then show it there.
Then we're supposed to decide if we need a separate DevStats instance for every single repository (which is not needed IMHO).
@dankohn ?

Another question is the priority of this task (in comparison to #45) and also how about icons for this project(s) and how about connecting all this stuff together opencontainers <-> CNCF projects?

**Comment by dankohn** [comment]
Yes, one instance for all OCI with each project being a repo group is fine.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
So maybe just include all repos listed in this org, instead of limiting to 5?
It will also handle any new repos created automagically.

This is the current list of repos and their date-ranges (eventual renames):
![screen shot 2018-02-08 at 07 30 56](https://user-images.githubusercontent.com/2469783/35958639-147d450e-0ca2-11e8-8d3a-6e1efea58a83.png)
![screen shot 2018-02-08 at 07 31 17](https://user-images.githubusercontent.com/2469783/35958640-14973bee-0ca2-11e8-863e-b15d942cc0a4.png)

https://docs.google.com/spreadsheets/d/1c50jfpOdbbW5KTn-ABQ8sTuktx3dkiNtOucb7KpAtLU/edit?usp=sharing

Anyway, starting to work on this, which repo is the "main" one?

And when we're putting all projects in a single DevStats instance, the best name would be:
- Prod: devstats.opencontainers.io ? or I can make it all.devstats.opencontainers.io (I think there is no sense to call it opencontainers.devstats.opencontainers.io)
- Test: opencontainsers.cncftest.io (this is easy).

**Comment by dankohn** [comment]
runc

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
Let's just do 5 for now, please. The others aren't important.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
OK, I'll fix then.
I'm finishing test instance - it will include all.
When I'm finished with this, I'll add restriction to only fetch those 5 and regenerate data - it will just work, but now I'm in the middle of importing dashboards here:
https://opencontainers.cncftest.io

At least I've guessted `runc` correctly :-D

**Comment by lukaszgryglicki** [comment]
Actually after BigQuery analysis it requires 7 repos:
- image-tools
- image-spec
- runtime-tools + ocitools (ocitools was the previous name)
- runtime-spec + specs (specs was the previous name)
- runc

See: https://docs.google.com/spreadsheets/d/1c50jfpOdbbW5KTn-ABQ8sTuktx3dkiNtOucb7KpAtLU/edit#gid=1340258988

I'll add this to `projects.yaml` and regenerate data.

**Comment by lukaszgryglicki** [comment]
OK `projects.yaml` updated: https://github.com/cncf/devstats/commit/be3c40dd17c2d84f522b4076154114ffc1837a6f
Regenerating psql data and then influx data.

**Comment by dankohn** [comment]
They only want to see 5 sub-repos. Can you please merge ocitools and specs
into their successors.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
I did, even before:
https://github.com/cncf/devstats/blob/master/scripts/opencontainers/repo_groups.sql#L8
https://github.com/cncf/devstats/blob/master/scripts/opencontainers/repo_groups.sql#L21

Now data is regenerating and will contain 5 repo groups, 2 of them will contain 2 repos.
The current state is that we have ALL possible repos grouped in repo groups (there were 4 repo renames).

**Comment by lukaszgryglicki** [comment]
Implemented on the test server: https://opencontainers.cncftest.io/d/000000025/activity-repository-groups?orgId=1
Production expected tomorrow.

**Comment by lukaszgryglicki** [comment]
Finished on production: https://all.devstats.opencontainers.org
