### ISSUE TITLE
Chart Request: open issues/PRs by milestone

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#77]
Request: Count of open issues and open PRs by milestone, as a line graph.  Should be filterable by SIG.

I really only care about kubernetes/kubernetes for this, so filtering down to that would also be nice.

**Comment by jberkus** [comment]
In the best of all possible worlds, I'd be able to somehow add vertical lines showing release cycle dates, or even comparable by days for each release date.

**Comment by lukaszgryglicki** [comment]
I'm working on this but I suspect there will be not enough data.
Why?
- We need the issue to have a milestone first, then it needs to have SIG label and finally only `kubernetes/kubernetes` - I'll check what I can get.
- But should I limit entire dashboard to just k/k or add standard repository group (as most charts do) but default its selection to "Kubernetes" (which means just the main repo but including its [name changes in time](https://github.com/cncf/devstats/blob/master/scripts/kubernetes/repo_groups.sql#L2-L6))?

The second question - how it should look like?
- Two dropdowns: SIG & Milestone: and then 2 line charts "open PRs" and "Open Issues"?
- SIG drop down and then stacked chart of Milestones PR (one panel) and another stacked chart of Milestone Issues (another panel)?
- SIG drop down and then a chart of Milestones PR (one panel) and another chart of Milestone Issues (another panel) (bot charts with multiple lines - one line per SIG)?
- Should it count issues opened in a given date period (like 7 days MA, Day, Week etc.) or should it show the number of issues that were opened in a given point in time, in this case, we don't need Period drop down, we will just use daily values each day? So value for 2017-12-10 will mean how many issues/PR were opened at this particular time. I'm assuming this.

Vertical lines showing release cycles:
- I can just add annotations - like other dashboards do, you can then use their dates to select the date range from top right date range selector). If you want some summary values using inter-related dates, you probably need "annotations date range selector", there is an [issue for this](https://github.com/cncf/devstats/issues/29) - it requires some work on the Grafana side, it is possible to select custom date ranges in tabular dashboards.
- Actually, I'll just add annotations as everywhere, but I need more info what exactly you need here.

So I will implement approach with:
- SIG drop-down to filter by SIG
- Milestone drop-down - to filter by Milestone
-  No repo group drop-down, it will just show values for kubernetes/kubernetes (or other main repo names from the past)
- It will show the count of issues/PR's at the given point in time, so there will be no period drop-down, values will be calculated daily (so the chart will show the number of open PRs/issues for every day).
- It will show releases annotations.

I expect many corrections/clarifications/feedback here, so I will just implement first draft version - without docs and test coverage, to avoid correcting docs and tests after feedback is received.

**Comment by lukaszgryglicki** [comment]
This is the very very very first SQL that returns correct data: https://github.com/cncf/devstats/blob/master/metrics/kubernetes/open_prs_sigs_milestones.sql

Now I need to add "All" entry and then create Milestones tags, dropdown etc.
Then I need to create similar SQL for issues.

But my biggest concern is gone - performance, I was afraid that indexes and current structure won't handle this fast, but query only takes about 1.2s so it is OK (we have a lot slower queries already, the slowest being PRs rebase).

**Comment by lukaszgryglicki** [comment]
First preview ready: https://k8s.devstats.cncf.io/d/IIUa5kezk/open-issues-prs-by-milestone?orgId=1
- It shows values for open PRs/Issues daily (each value is the number of open issues and open PRs in given SIG & Milestone that day)
- There is no period selection (it has no sense when showing state at given point in time, not the number of something that happened between period start and end)
- There is a SIG dropdown, and special value 'All' (All also includes issues/PRs not labeled with any SIG at all).
- There is a Milestone drop-down, it shows some top Milestones (used on most issues) + 'All; (All also includes issues/PRs not assigned to any milestone).
- Note that some issues can be in multiple SIGs, so can be visible in a few SIGs instead of one (I'm choosing the final issue state before the point in time, some of them can have few SIG labels assigned).
- K8s releases are shown as vertical lines (annotations).
- Values are calculated from main Kubernetes repo as requested (hardcoded in metric SQL, no repository group dropdown in this dashboard).

SQL are here:
- [open issues](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/open_issues_sigs_milestones.sql).
- [open PRs](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/open_prs_sigs_milestones.sql).
- metric defined [here](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/metrics.yaml#L168-L175).
- milestone tags defined [here](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/idb_tags.yaml#L72-L76) using [this](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/milestones_tags_with_all.sql) select.
- dashboard JSON [here](https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/open_issues_prs_by_milestone.json).

There is no test coverage and no documentation because I'm expecting some feedback. If approved I'll add test coverage & documentation.

Few screenshots:
![screen shot 2018-02-22 at 13 28 01](https://user-images.githubusercontent.com/2469783/36538928-694742ae-17d5-11e8-955a-2807d7fe6ef8.png)
![screen shot 2018-02-22 at 13 26 25](https://user-images.githubusercontent.com/2469783/36538929-69637302-17d5-11e8-88f3-a77ebd40ddf7.png)
![screen shot 2018-02-22 at 13 26 42](https://user-images.githubusercontent.com/2469783/36538930-697f3bfa-17d5-11e8-94e8-a772bfd1ee9b.png)
![screen shot 2018-02-22 at 13 28 48](https://user-images.githubusercontent.com/2469783/36538931-69a15c4e-17d5-11e8-8a27-9bd074f6b672.png)
![screen shot 2018-02-22 at 13 26 48](https://user-images.githubusercontent.com/2469783/36538932-69bf9542-17d5-11e8-86f9-05c9ca1fdc30.png)
![screen shot 2018-02-22 at 13 29 03](https://user-images.githubusercontent.com/2469783/36538933-69de4fd2-17d5-11e8-8631-12f32f9d1ae1.png)
![screen shot 2018-02-22 at 13 27 01](https://user-images.githubusercontent.com/2469783/36538934-69fecf8c-17d5-11e8-8539-df89e644ff18.png)
![screen shot 2018-02-22 at 13 29 12](https://user-images.githubusercontent.com/2469783/36538935-6a1bd7da-17d5-11e8-9222-f0524a8750b4.png)
![screen shot 2018-02-22 at 13 27 17](https://user-images.githubusercontent.com/2469783/36538936-6a395c88-17d5-11e8-9500-0477027a9fdb.png)
![screen shot 2018-02-22 at 13 29 29](https://user-images.githubusercontent.com/2469783/36538937-6a593af8-17d5-11e8-9f48-3352c14da95c.png)
![screen shot 2018-02-22 at 13 27 25](https://user-images.githubusercontent.com/2469783/36538938-6a736162-17d5-11e8-996c-74752916e724.png)
![screen shot 2018-02-22 at 13 29 48](https://user-images.githubusercontent.com/2469783/36538939-6a912cce-17d5-11e8-9125-d2aaeb524875.png)
![screen shot 2018-02-22 at 13 27 37](https://user-images.githubusercontent.com/2469783/36538940-6abbdc3a-17d5-11e8-8832-7efdf03e4ace.png)
![screen shot 2018-02-22 at 13 30 12](https://user-images.githubusercontent.com/2469783/36538941-6ad68e36-17d5-11e8-9d29-ca531513b556.png)
![screen shot 2018-02-22 at 13 27 42](https://user-images.githubusercontent.com/2469783/36538943-6b0b8f64-17d5-11e8-8a3e-cd0c3cd72200.png)
![screen shot 2018-02-22 at 13 27 52](https://user-images.githubusercontent.com/2469783/36538944-6b51a396-17d5-11e8-80ae-ceffc3e17cec.png)

Here I've manually selected v1.8 - v.1.9 from Grafana's date picker (top right):
![screen shot 2018-02-22 at 13 55 17](https://user-images.githubusercontent.com/2469783/36539737-172b00de-17d8-11e8-92ef-93fdc186accf.png)

Would be great if we could have "annotations dates list" as a predefined values to select on date picker UI.
For example you can select "date from": last month, day etc (what is there now) + drop-down to select any value from annotations query.
The same for "date to".
I've created such feature request on grafana/grafana long time ago, but unfortunatelly it seems that no one want to implement this.
If we really need that, I can spent few days forking Grafana and trying to implement this and creating PR finally - but I don't know whow long it would take and if they accept this PR.

**Comment by jberkus** [comment]
That's a really good start, and I can use that even the way it is now.

Here's what I'm trying to do: compare the number of open issues/PRs in a milestone for *this* release with the number of issues/PRs open for prior releases the same number of days before the expected release date.

I'm trying to determine if we have an actual, significant increase in the number of open issues/PRs for v1.10, or if that's just anecdotal.  

So the ideal "smart" chart, I think, would be to show each of several selected milestones based on "days before release", on the same chart, so that they could be directly compared.  However, that would have a bunch of requirements to make it work, such as having the release/slush/freeze dates in the DB, and also planned vs. actual release dates.  Let me know if you want to pursue doing this kind of chart, and I can map out what it should look like a bit more clearly.

I *also* need the chart you just created, simply because I need to see if PRs are catching up to issues for the current release, which it shows nicely.

Question: is milestone already in the time-series database?  That is, can I find out from InfluxDB how many open issues there were in 1.9 as of December 12th?

**Comment by jberkus** [comment]
Never mind, I answered my own question by checking: 

https://k8s.devstats.cncf.io/d/IIUa5kezk/open-issues-prs-by-milestone?orgId=1&from=1501630754665&to=1504395554666&var-sig_name=All&var-sig=all&var-milestone_name=v1.8&var-milestone=v1_8

Looks like we do have full timeline history for milestones.  Yay!

**Comment by grodrigues3** [comment]
I have a similar feature request.  For the features repo, we track issue by posted (e.g [v1.10](https://github.com/kubernetes/features/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.10)).  It'd be great if we could see a histogram of features per release per sig.  Something like a dropdown where I can select the milestone and the chart is a histogram of the feature count coming from each sig.

Edit.  this may be an identical request.  I'm just asking that the issues query (which represent features) also be run agains the k/features repo).

**Comment by lukaszgryglicki** [comment]
OK so it is just a matter of choosing repo?
If so I can add Repository drop-down or repository group drop down?
There will be a small delay because I have some work in progress atm.

**Comment by lukaszgryglicki** [comment]
I'm adding repository dropdown.
It will contain all repositories.
If that is too much, I will limit drop-down values (if needed).

**Comment by lukaszgryglicki** [comment]
Added repository drop-down: https://k8s.devstats.cncf.io/d/IIUa5kezk/open-issues-prs-by-milestone?orgId=1

For example:
- SIG: storage
- Milestone: v1.10
- Repo: kubernetes/features
https://k8s.devstats.cncf.io/d/IIUa5kezk/open-issues-prs-by-milestone?orgId=1&from=now-6M&to=now&var-sig_name=storage&var-sig=storage&var-milestone_name=v1.10&var-milestone=v1_10&var-repo_name=kubernetes%2Ffeatures&var-repo=kubernetes_features&var-full_name=Kubernetes
![screen shot 2018-02-27 at 07 44 13](https://user-images.githubusercontent.com/2469783/36714443-a0cad8ce-1b92-11e8-9cfc-cf35af597e54.png)
![screen shot 2018-02-27 at 07 44 20](https://user-images.githubusercontent.com/2469783/36714445-a0e8d02c-1b92-11e8-89fa-39b577804772.png)
![screen shot 2018-02-27 at 07 44 31](https://user-images.githubusercontent.com/2469783/36714446-a1066e8e-1b92-11e8-9678-a37ca53131c9.png)
![screen shot 2018-02-27 at 07 44 44](https://user-images.githubusercontent.com/2469783/36714449-a1785cd8-1b92-11e8-9e80-0d0132aec732.png)
![screen shot 2018-02-27 at 07 46 07](https://user-images.githubusercontent.com/2469783/36714451-a192938c-1b92-11e8-8a5a-6dbb6e9da8e4.png)
![screen shot 2018-02-27 at 07 55 41](https://user-images.githubusercontent.com/2469783/36714746-b179b63a-1b93-11e8-8c4e-bad6f24a172a.png)
![screen shot 2018-02-27 at 07 56 01](https://user-images.githubusercontent.com/2469783/36714747-b19b63a2-1b93-11e8-912d-9d2933528e65.png)


@grodrigues3 Is this OK?
Or maybe should I change something - like for example create another dashboard with multiple selection for SIG-s to display more of them stacked, or possibly multi select for Repo and stack them?
Or anything else?
@jberkus - you need to select Repo = kubernetes/kubernetes to have the same version as before.

**Comment by jberkus** [comment]
Ooops, PRs just vanished from the chart.  Fix?

**Comment by lukaszgryglicki** [comment]
My fault:
```
jberkus [7:40 PM]
around?  the new contributors graph appears to be broken

PRs aren't showing at all
https://k8s.devstats.cncf.io/d/IIUa5kezk/open-issues-prs-by-milestone?orgId=1&from=now-30d&to=now&var-sig_name=All&var-sig=all&var-milestone_name=v1.10&var-milestone=v1_10&var-repo_name=kubernetes%2Fkubernetes&var-repo=kubernetes_kubernetes&var-full_name=Kubernetes
sorry, NOT the new contributors graph.  the "PRs/Issues by Milestone" graph.

lukaszgryglicki [8:11 PM]
I probably know what’s wrong
but its 8PM in Poland atm
I’ll fix tomorrow
can you please add comment on the original issue
on cncf/devstats

jberkus [8:12 PM]
OK

lukaszgryglicki [8:12 PM]
as a reminder
you can just copy what you written here
I prefer to have everything public on the repo
this is just copy-paste issue
I didn’t changed series name when milestone is selected
note that if you select All - you’ll see data
just need to rename influx series name in SQL 9which I can do now) but then regenerate data is needed, stopping cron etc

jberkus [8:13 PM]
ok, thanks!

lukaszgryglicki [8:14 PM]
cu
gotta go
```
Will fix tomorrow first thing.

**Comment by lukaszgryglicki** [comment]
@jberkus decided to fix today.
Should be fixed now.
On both test & prod servers.
Let me know if works OK for you.

This was the cause for this: https://github.com/cncf/devstats/commit/3efab6e6933f0bed1b9812043e6f6be8383a2f5c#r27820594

**Comment by jberkus** [comment]
Fixed, thanks!
