### ISSUE TITLE
Dashboards as code

### ISSUE THREAD

**Issue by bergquist** [cncf/devstats.archive#9]
Some day in the future we really want to improve the experience for people who want to store their dashboards as files primarily rather then storing them in the database primarily. Until then I recommend using https://github.com/weaveworks/grafanalib great way of writing your dashboards are code instead of bloaty json files :)

**Comment by lukaszgryglicki** [comment]
That would require rewriting all our JSONs.
They aren't that bad atm.
Mainly because we're using templating.

I see one problem with templating - the real problem:
You can only put values for variables, something like "a,b,cde".

If You want to have different values than texts visible in the drop-down You need to export dashboard manually and update JSON with "text" and "value" pairs for each value.

Then if You edit that variable in Grafana UI again, then You "text" values will be cleared again and "text" will contain the same value as "value" column.

Solution might be something like setting variable via:
"a:This is what a value text is,some_value:Some value,..."

**Comment by lukaszgryglicki** [comment]
And would be great if all template variables can be called for their value or text.
So for example [[var]] would return variable value (default)
But there should also be  [[var:text]] that would return variable text.
Currently, Grafana is returning either value or text, depending on context.
In queries, it is returning variable value. In dashboard titles and drop-down, it is returning variable text.
But in dashboards description, it returns variables value (while I would prefer text here).

**Comment by bergquist** [comment]
@lukaszgryglicki that's two good points! Ill create issues for them in the grafana repo.

**Comment by lukaszgryglicki** [comment]
thx.

**Comment by lukaszgryglicki** [comment]
BTW @bergquist is it possible to have template variable values fetched from string value from InfluxDB?
I mean fetch drop-down values fromDB instead of setting variable values like "value1,value2,...,valueN" or even "value1:name1,value2:name2,...,valueN:nameN" ?

**Comment by bergquist** [comment]
You can query influxdb for tags and tag values in your templating queries. The queries can depend on each other. 

Example dashboard http://play.grafana.org/dashboard/db/influxdb-templated-queries?orgId=1
( json https://gist.github.com/bergquist/1f9e5cf56c65f4ea2260583c45527810 )
http://docs.grafana.org/features/datasources/influxdb/#templating

**Comment by lukaszgryglicki** [comment]
Seems promising, I'll research this.
Thanks!

**Comment by lukaszgryglicki** [comment]
Probably I'll have a problem with this.
It seems to return the list of values (according to documentation), while I need a list of values and names (as described https://github.com/cncf/gha2db/issues/9#issuecomment-333460117), so it will probably be a dead end.

**Comment by bergquist** [comment]
You could use the https://grafana.com/plugins/grafana-simple-json-datasource plugin to write a custom endpoints that return a list of {text: "friendly name", value: "some id"} objects. Its not as user friendly but its possible.

**Comment by lukaszgryglicki** [comment]
If I cannot use query variable here (will see in few hours) I'll leave "Repository group" drop down "as is".
Ideas was to select all distinct "Repository groups" from Postgres and then put that data "somewhere" in InfluxDB. And then fetch drop-down values from Influx.
Will see...

**Comment by lukaszgryglicki** [comment]
Not sure yet, but it *MAY* work.
I will have two tags on the same series.
One will be "repo_group_name" the other will be "repo_group_value"
I'll show `$repo_group_name` drop-down with: `show tag values with key = "repo_group_name"`
I'll add another dependent template variable `$repo_group_value` with: `show tag values with key = "repo_group_value" where repo_group_name =~ /$repo_group_name/`.
The other template variable should be invisible (if possible) and then if I change first drop down, the other will only have a single matching value that should be autoselected on change.

**Comment by lukaszgryglicki** [comment]
It *IS* working as described above - I'll update all dashboards to use dynamically generated drop-downs.

**Comment by lukaszgryglicki** [comment]
It is a working dashboard that gets:
-Drop down values & names from InfluxDB tags.
Exactly as described.
Names are taken from one tag and shown in the drop-down.
Values are taken from another tag (using first tag value as a where condition), another dropdown is invisible, but auto changes when first (visible) dropdown value changes.
Using this I have both [[repo_name]] variable (that holds user readable name) and [[repo]] variable (that holds value used as a part of data series name).
S this is fixing all problems described in this metric, automatically fetches all repository list from Influx (which is updated from Postgres by the cron job).
Please see this dashboard:
https://cncftest.io/dashboard/db/community-stats?orgId=1
![screen shot 2017-10-03 at 10 58 03](https://user-images.githubusercontent.com/2469783/31117485-3eb327f8-a82a-11e7-94a8-98375c385379.png)
You can also see details because You're "Read-only editor" by default!
@bergquist

**Comment by lukaszgryglicki** [comment]
Hmm maybe I should also think about the auto-generating list of metrics on some dashboards, like this one:
https://cncftest.io/dashboard/db/prs-merged-repository-groups?orgId=1
maybe the list of metrics should be generated from some kind of a DB query (if possible)?
Just thinking loudly...

**Comment by lukaszgryglicki** [comment]
@bergquist 
Managed to get this working.
Instead of repeating rows or panels which is not applicable here, I've used.
A query that contains multiple values (for all companies)
A template variable (multi-select variable that gets company list from InfluxDB tags)
Then I've used user selected multiple values in a select part of the metric.
So now this very complex dashboard gets all its data via single metric:
Dashboard: https://cncftest.io/dashboard/db/companies-stats?orgId=1
Its metric definition: `SELECT /^[[companies]]$/ FROM "company_[[repogroup]]_[[metric]]_[[period]]" WHERE $timeFilter`
And template variables (including one hidden that automatically changes when its "parent" drop-down changes):
![screen shot 2017-10-04 at 15 55 54](https://user-images.githubusercontent.com/2469783/31179590-a10aeb00-a91c-11e7-9c55-d15e921e59b2.png)
